### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by SiddhanthKapoor** [kalmux1/Huntmate#2]
Bug Found - The website when used on a smaller screen like mobile , the checklist button hides the content of the page and similarly the clear button hides content of the page , this makes the website unreadable at places !
I would like to get this issue assigned to me and hear back from you !

**Comment by kalmux1** [comment]
Thank you for reporting this issue! I appreciate your detailed feedback regarding the checklist and clear buttons obstructing the content on smaller screens. I'll assign the issue to you and look forward to your fix. Feel free to reach out if you need any clarification or assistance.

Best regards,
Kalmux
